[window]
padding = { x = 20, y = 30 }
decorations = "Transparent"
opacity = 0.90
blur = true
startup_mode = "Maximized"
dynamic_title = true

[font]
size = 14
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
